"""create messages table

Revision ID: f0c033a21392
Revises: 089035e503b4
Create Date: 2026-04-26 20:14:47.400019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0c033a21392'
down_revision: Union[str, Sequence[str], None] = '089035e503b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=False),
    sa.Column('receiver_id', sa.BigInteger(), nullable=False),
    sa.Column('msg_type', sa.Enum('text', 'image', 'file', 'audio', 'system', name='message_type'), server_default='text', nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=256), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('is_recalled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_msg_receiver_sender', 'messages', ['receiver_id', 'sender_id', 'created_at'], unique=False)
    op.create_index('idx_msg_sender_receiver', 'messages', ['sender_id', 'receiver_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_msg_sender_receiver', table_name='messages')
    op.drop_index('idx_msg_receiver_sender', table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
